Return syncmembers diffs to file and have it sent back
rmbarron/IronForgedBot pull request #23
Opened 2023-09-12 00:46 UTC by bennettsf

Here's a small addition to the syncmembers command that probably needs to be tested. Uses the same method as /breakdown where we create an output string and write it to a temp file to be displayed on the command being complete. 

The syncmembers log should display:
- added user w because they joined
- removed user x because they left the server
- skipped user y because they don't have a "Member" role
- skipped user z because they don't have a nickname in Discord

as requested. 

The logic is already there so it was as simple as adding the strings within the if/else statements.

Something I do have a concern about is for example, the remove_members() try/except statement fails on line 688, and how to handle the output string in such a case (which is why this obviously would need some testing).

2023-09-12 00:49 UTC, bennettsf commented
Also I believe the description for the check_role() function is a bit confusing as it shows "Check if a member has a leadership role." but in syncmembers case we're using it to check if the member has a "Member" role.

2023-09-13 01:58 UTC, rmbarron requested changes
Thank you for this! Comments are mostly nits; the important request is to update our existing unit test and add another line to the output for when we update and existing user.

2023-09-13 01:58 UTC, rmbarron commented on main.py
> +        output = '---Successfully synced members---\n'
nit: Lets leave this out of the output, as we return it in the line of text separate from the file.

2023-09-13 01:58 UTC, rmbarron commented on main.py
> +                output += f'skipped user {member} because they don\'t have a \"Member\" role\n'
nit: You don't need to escape the double quotes within a single quote string. Here and below.

```
~$ python3
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> m = 'no quote "double" quotes'
>>> m
'no quote "double" quotes'
```

2023-09-13 01:58 UTC, rmbarron commented on main.py
> +        path = os.path.join(self._tmp_dir_path, 'log_syncmembers.txt')
nit: WDYT about writing the file as `f'syncmembers_{caller.nick}.txt'` or `tmp_syncmembers.txt`?

I want to avoid the word `log` here as that has a different meaning. `Log` is meant more for when we log to a file or write to a specific changelog. This is just meant to be more convenient output for users.

2023-09-13 01:58 UTC, rmbarron commented on main.py
> +                f'Successfully synced ingots storage with current members!',
nit: This doesn't need to be an f string, it can just be a string. The prefixed `f` is only needed when applying formatting to the string, but this is a string literal.

2023-09-13 01:58 UTC, rmbarron commented on main.py
Could you update test_syncmembers[1] to assert the the file was written with our expected output for the users in that test? test_breakdown[2] has some prior art for asserting the text written to file[3]. For this one, we'll only have to patch out the builtins.open call and not requests.get.

[1] https://github.com/rmbarron/IronForgedBot/blob/main/main_test.py#L450
[2] https://github.com/rmbarron/IronForgedBot/blob/main/main_test.py#L187
[3] https://github.com/rmbarron/IronForgedBot/blob/main/main_test.py#L195-L202

2023-09-13 01:58 UTC, rmbarron commented on main.py
>              return
(Comment is actually about line 715)

We should also include a text line for when we changed an existing user.

2023-09-13 02:14 UTC, rmbarron commented on main.py
> +        output = '---Successfully synced members---\n'
Also, we don't really ~need the performance gains of efficient string manipulations for what we're doing, but it would be slightly more effective for `output` to be a list of strings, where we write `'\n'.join(output)` to create the necessary newlines.

As a bonus, its also a bit more readable and we don't need to remember to include \n directly.

Doc on the performance benefit is #6 in https://docs.python.org/3/library/stdtypes.html#common-sequence-operations

2023-10-10 01:53 UTC, bennettsf reviewed
This should be the code we worked on, plus a change to the output file name on L732 of main.py to the person who ran the command. Still getting practice navigating GitHub so if I did the pull request wrong let me know

2023-10-11 23:41 UTC, rmbarron commented
Thank you for the changes and adding a test!

2023-10-11 23:41 UTC, merged